// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(ffiFFI)
import ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * The FFI entry point. One per app; `begin_walk` (Task 7) hands out
 * per-session `WalkSession`s.
 */
public protocol MurmurEngineProtocol : AnyObject {
    
    /**
     * `Store::start_session` + persists the template key, hands back a
     * fresh per-session `WalkSession` (D4). Fallible across FFI (no panics):
     * a poisoned store lock or a store error surfaces to Swift as
     * `EngineError::BeginWalk` rather than crashing the host app.
     */
    func beginWalk(jobId: String?, template: String) throws  -> WalkSession
    
}

/**
 * The FFI entry point. One per app; `begin_walk` (Task 7) hands out
 * per-session `WalkSession`s.
 */
open class MurmurEngine:
    MurmurEngineProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_ffi_fn_clone_murmurengine(self.pointer, $0) }
    }
    /**
     * Fallible across FFI (uniffi throwing constructor): opening the store or
     * starting the runtime can fail on a real device, and a panic here would
     * crash the host app instead of letting Swift handle it.
     */
public convenience init(config: EngineConfig)throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypeEngineError.lift) {
    uniffi_ffi_fn_constructor_murmurengine_new(
        FfiConverterTypeEngineConfig.lower(config),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_ffi_fn_free_murmurengine(pointer, $0) }
    }

    

    
    /**
     * `Store::start_session` + persists the template key, hands back a
     * fresh per-session `WalkSession` (D4). Fallible across FFI (no panics):
     * a poisoned store lock or a store error surfaces to Swift as
     * `EngineError::BeginWalk` rather than crashing the host app.
     */
open func beginWalk(jobId: String?, template: String)throws  -> WalkSession {
    return try  FfiConverterTypeWalkSession.lift(try rustCallWithError(FfiConverterTypeEngineError.lift) {
    uniffi_ffi_fn_method_murmurengine_begin_walk(self.uniffiClonePointer(),
        FfiConverterOptionString.lower(jobId),
        FfiConverterString.lower(template),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMurmurEngine: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = MurmurEngine

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> MurmurEngine {
        return MurmurEngine(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: MurmurEngine) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MurmurEngine {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: MurmurEngine, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMurmurEngine_lift(_ pointer: UnsafeMutableRawPointer) throws -> MurmurEngine {
    return try FfiConverterTypeMurmurEngine.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMurmurEngine_lower(_ value: MurmurEngine) -> UnsafeMutableRawPointer {
    return FfiConverterTypeMurmurEngine.lower(value)
}




/**
 * Foreign-implemented listener — `with_foreign`, never `callback_interface`
 * (the boxed-trait-object-as-parameter shape fails to compile under uniffi
 * 0.28+: mozilla/uniffi-rs#2797). Stored/passed as `Arc<dyn WalkEventListener>`.
 */
public protocol WalkEventListener : AnyObject {
    
    func onEvent(event: WalkEvent) 
    
}

/**
 * Foreign-implemented listener — `with_foreign`, never `callback_interface`
 * (the boxed-trait-object-as-parameter shape fails to compile under uniffi
 * 0.28+: mozilla/uniffi-rs#2797). Stored/passed as `Arc<dyn WalkEventListener>`.
 */
open class WalkEventListenerImpl:
    WalkEventListener {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_ffi_fn_clone_walkeventlistener(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_ffi_fn_free_walkeventlistener(pointer, $0) }
    }

    

    
open func onEvent(event: WalkEvent) {try! rustCall() {
    uniffi_ffi_fn_method_walkeventlistener_on_event(self.uniffiClonePointer(),
        FfiConverterTypeWalkEvent.lower(event),$0
    )
}
}
    

}
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceWalkEventListener {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    static var vtable: UniffiVTableCallbackInterfaceWalkEventListener = UniffiVTableCallbackInterfaceWalkEventListener(
        onEvent: { (
            uniffiHandle: UInt64,
            event: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeWalkEventListener.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onEvent(
                     event: try FfiConverterTypeWalkEvent.lift(event)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterTypeWalkEventListener.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface WalkEventListener: handle missing in uniffiFree")
            }
        }
    )
}

private func uniffiCallbackInitWalkEventListener() {
    uniffi_ffi_fn_init_callback_vtable_walkeventlistener(&UniffiCallbackInterfaceWalkEventListener.vtable)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWalkEventListener: FfiConverter {
    fileprivate static var handleMap = UniffiHandleMap<WalkEventListener>()

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = WalkEventListener

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> WalkEventListener {
        return WalkEventListenerImpl(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: WalkEventListener) -> UnsafeMutableRawPointer {
        guard let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: handleMap.insert(obj: value))) else {
            fatalError("Cast to UnsafeMutableRawPointer failed")
        }
        return ptr
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WalkEventListener {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: WalkEventListener, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWalkEventListener_lift(_ pointer: UnsafeMutableRawPointer) throws -> WalkEventListener {
    return try FfiConverterTypeWalkEventListener.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWalkEventListener_lower(_ value: WalkEventListener) -> UnsafeMutableRawPointer {
    return FfiConverterTypeWalkEventListener.lower(value)
}




/**
 * One recording session's bridge state. `finish` lands in Task 8.
 */
public protocol WalkSessionProtocol : AnyObject {
    
    /**
     * Fire-and-forget (D7): writes the transcript chunk through a short
     * scoped `Store` lock, then spawns the live-extraction tick. The tick
     * acquires the EXTRACTOR mutex (never the `Store` lock) across
     * `maybe_extract().await` — the `Store`'s own scoped guards inside
     * `maybe_extract` are the only place it's locked during the tick.
     */
    func appendTranscript(text: String) 
    
    /**
     * D6/D9: `end_and_record_session` + `SessionProcessor::process`, then
     * the terminal swap snapshot + the structured document.
     *
     * Three degrade paths, none of which may panic across the FFI boundary
     * (a `uniffi::export`ed async fn returns a bare `DocumentPayload`, not a
     * `Result` — an unwind here is a fatal crash in the host app, not a
     * catchable error):
     * - `end_and_record_session` fails (most commonly: a second `finish()`
     * call on an already-ended session) -> `degraded_document()`.
     * - phase B ran but the transcript was empty/whitespace-only, so
     * `murmur-core`'s pipeline short-circuited before building a document
     * artifact -> a truthful, non-queued `partial_document`.
     * - phase B failed outright (offline/LLM-down, D9) -> a queued partial
     * document built from the live board — capture is never lost.
     */
    func finish() async  -> DocumentPayload
    
    /**
     * Stores the listener (fresh per session — D3/HANDOFF per-session
     * streams).
     */
    func setEventListener(listener: WalkEventListener) 
    
    /**
     * Number of store faults swallowed by fire-and-forget live ticks so far
     * (carry-note 4). A nonzero count means a tick's store access failed (a
     * poisoned lock, a sqlite/NotFound error) — never a model/offline pass,
     * which is swallowed by design (D9). The UI can poll this to surface a
     * "capture degraded" hint. Lock-free read.
     */
    func tickStoreFaultCount()  -> UInt64
    
}

/**
 * One recording session's bridge state. `finish` lands in Task 8.
 */
open class WalkSession:
    WalkSessionProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_ffi_fn_clone_walksession(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_ffi_fn_free_walksession(pointer, $0) }
    }

    

    
    /**
     * Fire-and-forget (D7): writes the transcript chunk through a short
     * scoped `Store` lock, then spawns the live-extraction tick. The tick
     * acquires the EXTRACTOR mutex (never the `Store` lock) across
     * `maybe_extract().await` — the `Store`'s own scoped guards inside
     * `maybe_extract` are the only place it's locked during the tick.
     */
open func appendTranscript(text: String) {try! rustCall() {
    uniffi_ffi_fn_method_walksession_append_transcript(self.uniffiClonePointer(),
        FfiConverterString.lower(text),$0
    )
}
}
    
    /**
     * D6/D9: `end_and_record_session` + `SessionProcessor::process`, then
     * the terminal swap snapshot + the structured document.
     *
     * Three degrade paths, none of which may panic across the FFI boundary
     * (a `uniffi::export`ed async fn returns a bare `DocumentPayload`, not a
     * `Result` — an unwind here is a fatal crash in the host app, not a
     * catchable error):
     * - `end_and_record_session` fails (most commonly: a second `finish()`
     * call on an already-ended session) -> `degraded_document()`.
     * - phase B ran but the transcript was empty/whitespace-only, so
     * `murmur-core`'s pipeline short-circuited before building a document
     * artifact -> a truthful, non-queued `partial_document`.
     * - phase B failed outright (offline/LLM-down, D9) -> a queued partial
     * document built from the live board — capture is never lost.
     */
open func finish()async  -> DocumentPayload {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ffi_fn_method_walksession_finish(
                    self.uniffiClonePointer()
                    
                )
            },
            pollFunc: ffi_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeDocumentPayload.lift,
            errorHandler: nil
            
        )
}
    
    /**
     * Stores the listener (fresh per session — D3/HANDOFF per-session
     * streams).
     */
open func setEventListener(listener: WalkEventListener) {try! rustCall() {
    uniffi_ffi_fn_method_walksession_set_event_listener(self.uniffiClonePointer(),
        FfiConverterTypeWalkEventListener.lower(listener),$0
    )
}
}
    
    /**
     * Number of store faults swallowed by fire-and-forget live ticks so far
     * (carry-note 4). A nonzero count means a tick's store access failed (a
     * poisoned lock, a sqlite/NotFound error) — never a model/offline pass,
     * which is swallowed by design (D9). The UI can poll this to surface a
     * "capture degraded" hint. Lock-free read.
     */
open func tickStoreFaultCount() -> UInt64 {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_ffi_fn_method_walksession_tick_store_fault_count(self.uniffiClonePointer(),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWalkSession: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = WalkSession

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> WalkSession {
        return WalkSession(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: WalkSession) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WalkSession {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: WalkSession, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWalkSession_lift(_ pointer: UnsafeMutableRawPointer) throws -> WalkSession {
    return try FfiConverterTypeWalkSession.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWalkSession_lower(_ value: WalkSession) -> UnsafeMutableRawPointer {
    return FfiConverterTypeWalkSession.lower(value)
}


/**
 * One item on the live/authoritative board. `right` and `photo_count` have
 * no core equivalent yet (photo attachment sync is Deferred 6; `right` is
 * board-chrome text the Swift layer owns) — the projection defaults them so
 * the FFI boundary stays honest about what core actually knows.
 */
public struct BoardItem {
    public var id: String
    public var kind: String
    public var text: String
    public var right: String
    public var photoCount: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, kind: String, text: String, right: String, photoCount: UInt32) {
        self.id = id
        self.kind = kind
        self.text = text
        self.right = right
        self.photoCount = photoCount
    }
}



extension BoardItem: Equatable, Hashable {
    public static func ==(lhs: BoardItem, rhs: BoardItem) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.kind != rhs.kind {
            return false
        }
        if lhs.text != rhs.text {
            return false
        }
        if lhs.right != rhs.right {
            return false
        }
        if lhs.photoCount != rhs.photoCount {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(kind)
        hasher.combine(text)
        hasher.combine(right)
        hasher.combine(photoCount)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBoardItem: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BoardItem {
        return
            try BoardItem(
                id: FfiConverterString.read(from: &buf), 
                kind: FfiConverterString.read(from: &buf), 
                text: FfiConverterString.read(from: &buf), 
                right: FfiConverterString.read(from: &buf), 
                photoCount: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: BoardItem, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.kind, into: &buf)
        FfiConverterString.write(value.text, into: &buf)
        FfiConverterString.write(value.right, into: &buf)
        FfiConverterUInt32.write(value.photoCount, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBoardItem_lift(_ buf: RustBuffer) throws -> BoardItem {
    return try FfiConverterTypeBoardItem.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBoardItem_lower(_ value: BoardItem) -> RustBuffer {
    return FfiConverterTypeBoardItem.lower(value)
}


public struct DocLine {
    public var id: String
    public var title: String
    public var detail: String
    public var qty: String
    public var amountCents: Int64?
    public var section: String?
    /**
     * Template-aware (D2a) — set by the `build_document` tool, never derived
     * by the FFI layer from `amount_cents == None`.
     */
    public var isGap: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, title: String, detail: String, qty: String, amountCents: Int64?, section: String?, 
        /**
         * Template-aware (D2a) — set by the `build_document` tool, never derived
         * by the FFI layer from `amount_cents == None`.
         */isGap: Bool) {
        self.id = id
        self.title = title
        self.detail = detail
        self.qty = qty
        self.amountCents = amountCents
        self.section = section
        self.isGap = isGap
    }
}



extension DocLine: Equatable, Hashable {
    public static func ==(lhs: DocLine, rhs: DocLine) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.title != rhs.title {
            return false
        }
        if lhs.detail != rhs.detail {
            return false
        }
        if lhs.qty != rhs.qty {
            return false
        }
        if lhs.amountCents != rhs.amountCents {
            return false
        }
        if lhs.section != rhs.section {
            return false
        }
        if lhs.isGap != rhs.isGap {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(title)
        hasher.combine(detail)
        hasher.combine(qty)
        hasher.combine(amountCents)
        hasher.combine(section)
        hasher.combine(isGap)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDocLine: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DocLine {
        return
            try DocLine(
                id: FfiConverterString.read(from: &buf), 
                title: FfiConverterString.read(from: &buf), 
                detail: FfiConverterString.read(from: &buf), 
                qty: FfiConverterString.read(from: &buf), 
                amountCents: FfiConverterOptionInt64.read(from: &buf), 
                section: FfiConverterOptionString.read(from: &buf), 
                isGap: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: DocLine, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterString.write(value.detail, into: &buf)
        FfiConverterString.write(value.qty, into: &buf)
        FfiConverterOptionInt64.write(value.amountCents, into: &buf)
        FfiConverterOptionString.write(value.section, into: &buf)
        FfiConverterBool.write(value.isGap, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDocLine_lift(_ buf: RustBuffer) throws -> DocLine {
    return try FfiConverterTypeDocLine.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDocLine_lower(_ value: DocLine) -> RustBuffer {
    return FfiConverterTypeDocLine.lower(value)
}


public struct DocumentPayload {
    public var docKind: String
    public var docNumber: UInt64
    public var jobDateUnix: UInt64
    public var totalKind: String
    public var totalLabelKey: String
    public var staticTotalCents: Int64?
    public var lines: [DocLine]
    /**
     * True when `finish()` degraded offline (D9) — a partial document built
     * from live items, all gaps, capture never lost.
     */
    public var queued: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(docKind: String, docNumber: UInt64, jobDateUnix: UInt64, totalKind: String, totalLabelKey: String, staticTotalCents: Int64?, lines: [DocLine], 
        /**
         * True when `finish()` degraded offline (D9) — a partial document built
         * from live items, all gaps, capture never lost.
         */queued: Bool) {
        self.docKind = docKind
        self.docNumber = docNumber
        self.jobDateUnix = jobDateUnix
        self.totalKind = totalKind
        self.totalLabelKey = totalLabelKey
        self.staticTotalCents = staticTotalCents
        self.lines = lines
        self.queued = queued
    }
}



extension DocumentPayload: Equatable, Hashable {
    public static func ==(lhs: DocumentPayload, rhs: DocumentPayload) -> Bool {
        if lhs.docKind != rhs.docKind {
            return false
        }
        if lhs.docNumber != rhs.docNumber {
            return false
        }
        if lhs.jobDateUnix != rhs.jobDateUnix {
            return false
        }
        if lhs.totalKind != rhs.totalKind {
            return false
        }
        if lhs.totalLabelKey != rhs.totalLabelKey {
            return false
        }
        if lhs.staticTotalCents != rhs.staticTotalCents {
            return false
        }
        if lhs.lines != rhs.lines {
            return false
        }
        if lhs.queued != rhs.queued {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(docKind)
        hasher.combine(docNumber)
        hasher.combine(jobDateUnix)
        hasher.combine(totalKind)
        hasher.combine(totalLabelKey)
        hasher.combine(staticTotalCents)
        hasher.combine(lines)
        hasher.combine(queued)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDocumentPayload: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DocumentPayload {
        return
            try DocumentPayload(
                docKind: FfiConverterString.read(from: &buf), 
                docNumber: FfiConverterUInt64.read(from: &buf), 
                jobDateUnix: FfiConverterUInt64.read(from: &buf), 
                totalKind: FfiConverterString.read(from: &buf), 
                totalLabelKey: FfiConverterString.read(from: &buf), 
                staticTotalCents: FfiConverterOptionInt64.read(from: &buf), 
                lines: FfiConverterSequenceTypeDocLine.read(from: &buf), 
                queued: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: DocumentPayload, into buf: inout [UInt8]) {
        FfiConverterString.write(value.docKind, into: &buf)
        FfiConverterUInt64.write(value.docNumber, into: &buf)
        FfiConverterUInt64.write(value.jobDateUnix, into: &buf)
        FfiConverterString.write(value.totalKind, into: &buf)
        FfiConverterString.write(value.totalLabelKey, into: &buf)
        FfiConverterOptionInt64.write(value.staticTotalCents, into: &buf)
        FfiConverterSequenceTypeDocLine.write(value.lines, into: &buf)
        FfiConverterBool.write(value.queued, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDocumentPayload_lift(_ buf: RustBuffer) throws -> DocumentPayload {
    return try FfiConverterTypeDocumentPayload.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDocumentPayload_lower(_ value: DocumentPayload) -> RustBuffer {
    return FfiConverterTypeDocumentPayload.lower(value)
}


/**
 * Config crossing the FFI boundary. `api_key` is an opaque `String` from the
 * iOS Keychain and must NEVER be logged — `Debug` is hand-written (never
 * derived) so it always redacts the key, even if a field is added later.
 */
public struct EngineConfig {
    public var dbPath: String
    public var deviceId: String
    public var apiKey: String
    public var baseUrl: String?
    public var modelLive: String
    public var modelProcessing: String
    public var modelReflection: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(dbPath: String, deviceId: String, apiKey: String, baseUrl: String?, modelLive: String, modelProcessing: String, modelReflection: String) {
        self.dbPath = dbPath
        self.deviceId = deviceId
        self.apiKey = apiKey
        self.baseUrl = baseUrl
        self.modelLive = modelLive
        self.modelProcessing = modelProcessing
        self.modelReflection = modelReflection
    }
}



extension EngineConfig: Equatable, Hashable {
    public static func ==(lhs: EngineConfig, rhs: EngineConfig) -> Bool {
        if lhs.dbPath != rhs.dbPath {
            return false
        }
        if lhs.deviceId != rhs.deviceId {
            return false
        }
        if lhs.apiKey != rhs.apiKey {
            return false
        }
        if lhs.baseUrl != rhs.baseUrl {
            return false
        }
        if lhs.modelLive != rhs.modelLive {
            return false
        }
        if lhs.modelProcessing != rhs.modelProcessing {
            return false
        }
        if lhs.modelReflection != rhs.modelReflection {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(dbPath)
        hasher.combine(deviceId)
        hasher.combine(apiKey)
        hasher.combine(baseUrl)
        hasher.combine(modelLive)
        hasher.combine(modelProcessing)
        hasher.combine(modelReflection)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEngineConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EngineConfig {
        return
            try EngineConfig(
                dbPath: FfiConverterString.read(from: &buf), 
                deviceId: FfiConverterString.read(from: &buf), 
                apiKey: FfiConverterString.read(from: &buf), 
                baseUrl: FfiConverterOptionString.read(from: &buf), 
                modelLive: FfiConverterString.read(from: &buf), 
                modelProcessing: FfiConverterString.read(from: &buf), 
                modelReflection: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: EngineConfig, into buf: inout [UInt8]) {
        FfiConverterString.write(value.dbPath, into: &buf)
        FfiConverterString.write(value.deviceId, into: &buf)
        FfiConverterString.write(value.apiKey, into: &buf)
        FfiConverterOptionString.write(value.baseUrl, into: &buf)
        FfiConverterString.write(value.modelLive, into: &buf)
        FfiConverterString.write(value.modelProcessing, into: &buf)
        FfiConverterString.write(value.modelReflection, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEngineConfig_lift(_ buf: RustBuffer) throws -> EngineConfig {
    return try FfiConverterTypeEngineConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEngineConfig_lower(_ value: EngineConfig) -> RustBuffer {
    return FfiConverterTypeEngineConfig.lower(value)
}


/**
 * Fallible-path errors that cross the FFI boundary as a thrown error rather
 * than a panic (Plan 07 CANON: no panics across FFI). `flat_error` means the
 * Swift side receives the variant plus its `Display` message — no api key is
 * ever in these strings (store/runtime/session errors only).
 */
public enum EngineError {

    
    
    /**
     * The on-device store could not be opened (bad path, permissions, corrupt
     * db). Recoverable by the host — surface, don't crash.
     */
    case Store(message: String)
    
    /**
     * The bridge's tokio runtime could not be started.
     */
    case Runtime(message: String)
    
    /**
     * A walk could not be started (store lock, session insert, template set).
     */
    case BeginWalk(message: String)
    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEngineError: FfiConverterRustBuffer {
    typealias SwiftType = EngineError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EngineError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Store(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .Runtime(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .BeginWalk(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: EngineError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .Store(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .Runtime(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .BeginWalk(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))

        
        }
    }
}


extension EngineError: Equatable, Hashable {}

extension EngineError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * A whole-board snapshot per live pass (D3) — not per-item diffs. The
 * live→authoritative swap at `finish()` is just the terminal snapshot this
 * carries.
 */

public enum WalkEvent {
    
    case boardUpdated(items: [BoardItem]
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWalkEvent: FfiConverterRustBuffer {
    typealias SwiftType = WalkEvent

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WalkEvent {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .boardUpdated(items: try FfiConverterSequenceTypeBoardItem.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: WalkEvent, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .boardUpdated(items):
            writeInt(&buf, Int32(1))
            FfiConverterSequenceTypeBoardItem.write(items, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWalkEvent_lift(_ buf: RustBuffer) throws -> WalkEvent {
    return try FfiConverterTypeWalkEvent.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWalkEvent_lower(_ value: WalkEvent) -> RustBuffer {
    return FfiConverterTypeWalkEvent.lower(value)
}



extension WalkEvent: Equatable, Hashable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionInt64: FfiConverterRustBuffer {
    typealias SwiftType = Int64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeBoardItem: FfiConverterRustBuffer {
    typealias SwiftType = [BoardItem]

    public static func write(_ value: [BoardItem], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeBoardItem.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [BoardItem] {
        let len: Int32 = try readInt(&buf)
        var seq = [BoardItem]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeBoardItem.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeDocLine: FfiConverterRustBuffer {
    typealias SwiftType = [DocLine]

    public static func write(_ value: [DocLine], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeDocLine.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [DocLine] {
        let len: Int32 = try readInt(&buf)
        var seq = [DocLine]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeDocLine.read(from: &buf))
        }
        return seq
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_MAYBE_READY: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call uniffiEnsureInitialized() since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                uniffiFutureContinuationCallback,
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_ffi_checksum_method_murmurengine_begin_walk() != 41375) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ffi_checksum_method_walkeventlistener_on_event() != 10314) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ffi_checksum_method_walksession_append_transcript() != 45442) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ffi_checksum_method_walksession_finish() != 48721) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ffi_checksum_method_walksession_set_event_listener() != 4564) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ffi_checksum_method_walksession_tick_store_fault_count() != 17762) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ffi_checksum_constructor_murmurengine_new() != 42343) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitWalkEventListener()
    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all