#!/usr/bin/env bash
# Generates SitewalkGallery.xcodeproj, injecting the API key so the app runs the
# REAL murmur-core engine instead of the demo engine.
#
# Secret flow (no secret ever touches a tracked file):
#   repo-root .env  ANTHROPIC_API_KEY  ->  gitignored apps/ios/project.local.yml
#   (build setting PPQ_API_KEY)  ->  xcodebuild expands $(PPQ_API_KEY) into the
#   built app's Info.plist at build time. The tracked Info.plist/project.yml only
#   ever hold the literal "$(PPQ_API_KEY)".
#
# The .env var is named ANTHROPIC_API_KEY; the app's Info.plist key is the
# historical PPQ_API_KEY — this script bridges the two names.
#
# Usage: cd apps/ios && ./generate.sh   (then build with xcodebuild / XcodeBuildMCP)
set -euo pipefail
cd "$(dirname "$0")"                 # apps/ios
REPO_ROOT="$(cd ../.. && pwd)"
ENV_FILE="$REPO_ROOT/.env"
LOCAL="project.local.yml"

# Resolve the key: explicit env wins, else read from .env. Never printed.
KEY=""
if [ -n "${ANTHROPIC_API_KEY:-}" ]; then
  KEY="$ANTHROPIC_API_KEY"
elif [ -f "$ENV_FILE" ] && grep -qE '^ANTHROPIC_API_KEY=' "$ENV_FILE"; then
  KEY="$(grep -E '^ANTHROPIC_API_KEY=' "$ENV_FILE" | head -1 | cut -d= -f2-)"
fi

if [ -z "$KEY" ]; then
  echo "WARN: no ANTHROPIC_API_KEY in env or $ENV_FILE." >&2
  echo "      The app will build against the DEMO engine (no real LLM)." >&2
fi

# Write the gitignored local spec (0600). Value is never echoed.
umask 077
cat > "$LOCAL" <<EOF
# AUTO-GENERATED by ./generate.sh from .env — gitignored, never commit.
settings:
  base:
    PPQ_API_KEY: "$KEY"
EOF

xcodegen generate
echo "==> generated SitewalkGallery.xcodeproj (real engine active when a key was found)"
